# Generated by Django 4.1.5 on 2023-01-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_of_views',
            field=models.SmallIntegerField(default=0, editable=False, verbose_name='Количество просмотров'),
        ),
    ]
