version: "3.9"

services:

  postgres:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - db_network
    volumes:
      - .postgres-data:/var/lib/postgresql/data
    container_name: django_postgres

  django_app:
    build: .
    command: gunicorn blog.wsgi:application --bind 0.0.0.0:8000
    restart: always
    ports: ["8000:8000",]
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    links:
      - postgres
    networks:
      - nginx_network
      - db_network
    depends_on:
      - postgres
    volumes:
      - .log:/src/app/log
      - static:/src/app/static
    container_name: django_app

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static:/src/app/static
    ports:
      - 80:80
    networks:
        - nginx_network
    depends_on:
      - django_app

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  static:
  .log:
  .postgres-data:
